---
# Weather for today from Home Assistant Accuweather plugin

text_sensor:
  - platform: homeassistant
    entity_id: weather.openweathermap
    id: weather_condition
    on_value:
        then:  !include { file: weather_icons_update.yaml, vars: { size: "${size}", id: weather_condition_icon, input_id: weather_condition  } }

  - platform: homeassistant
    entity_id: weather.openweathermap
    attribute: temperature
    id: temperature
    on_value:
        then:
          # Update weather_condition
          - lvgl.label.update:
              id: weather_temperature_today
              text:
                format: "%sÂ°"
                args: [ 'id(temperature).state.c_str()' ]

  # Condition text
  - platform: homeassistant
    entity_id: weather.openweathermap
    id: condition_today
    on_value:
        then:
          - lvgl.label.update:
              id: weather_condition_today
              text:
                format: "%s"
                args: [ 'id(condition_today).state.c_str()' ]