---
# Weather icons
# https://github.com/manifestinteractive/weather-underground-icons.git

image:
  - file: esphome-modular-lvgl-buttons/weather/assets/images/nt_clear.svg
    id: clear_night_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/cloudy.svg
    id: cloudy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/tstorms.svg
    id: exceptional_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/fog.svg
    id: fog_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/sleet.svg
    id: hail_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/chancetstorms.svg
    id: lightning_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/tstorms.svg
    id: lightning_rainy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/partlycloudy.svg
    id: partlycloudy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/rain.svg
    id: pouring_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/chancerain.svg
    id: rainy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/snow.svg
    id: snowy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/chancesleet.svg
    id: snowy_rainy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/sunny.svg
    id: sunny_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/windy.svg
    id: windy_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/unknown.svg
    id: unknown_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel

  - file: esphome-modular-lvgl-buttons/weather/assets/images/circle-slash.svg
    id: unavailable_${size}
    resize: ${size}x${size}
    type: RGB565
    transparency: alpha_channel
