# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: nunito_24
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # LCD backlight modes - Code in backlight.yaml
  # Day mode is set to Sunrise
  # Evening mode is set to sunset
  # Set Night mode  at Mightnight here
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Screen Size
  screen_height: '480'
  screen_width: '480'
  byte_order: big_endian  

esphome:
  name: "guition-4848s040"
  friendly_name: "Guition 4848s040"
  comment: "Guition ESP32-S3-4848S040 480px * 480px Smart Screen"
  includes:
    - <sstream>
    - <algorithm>
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page

logger:
  level: debug

# Time update script - This is run once per second. Use it to update any time related labels.
script:
  - id: time_update
    then:
      - lambda: |-
          // No operation

packages:
  # Generic configuration for ESP32 screens
  # SDL has no Wi-Fi
  wifi: !include esphome-modular-lvgl-buttons/common/wifi.yaml
  # Enable OTA updates with a status screen
  ota_screen: !include esphome-modular-lvgl-buttons/common/ota.yaml
  # All the colors
  colors: !include esphome-modular-lvgl-buttons/common/color.yaml
  # Some nice basic fonts
  fonts: !include esphome-modular-lvgl-buttons/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-modular-lvgl-buttons/common/mdi_glyph_substitutions.yaml
  # Some basic sensors
  sensors: !include esphome-modular-lvgl-buttons/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include esphome-modular-lvgl-buttons/common/theme_style.yaml
  # Include if your touch screen has a backlight. Also sets the time from HA
  backlight: !include esphome-modular-lvgl-buttons/common/backlignt_time.yaml

  # Harware description file
  hardware: !include esphome-modular-lvgl-buttons/hardware/guition-esp32-s3-4848s040.yaml
  
  # Basic boot screen with ESPHome logo and device diagnostic info
  loading_screen: !include esphome-modular-lvgl-buttons/pages/loading_480px.yaml
  info_screen: !include esphome-modular-lvgl-buttons/pages/info.yaml

  # This section will Update button state and relay state from Home Assistant
  # Any button that has real time updates needs a section here

  # Button 1 - Local relay button with state updates
  # ha_name will show up as a control in Home Assistant
  button_1_state: !include
    file: esphome-modular-lvgl-buttons/sensors/local_relay_button_state.yaml
    vars:
      uid: button_1
      ha_name: Light 1
      entity_id: internal_relay_1

  # Button 2 - Standard light button with state updates
  button_2_state: !include
    file: esphome-modular-lvgl-buttons/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_2
      entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
  # Button 4 - Standard light button with state updates including dimming
  button_4_state: !include
    file: esphome-modular-lvgl-buttons/sensors/dimmer_light_state.yaml
    vars:
      uid: button_4
      entity_id: light.athom_rgb_light_d93662_rgb_light_strip

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      bg_color: black
      bg_opa: cover
      <<: !include
        file: esphome-modular-lvgl-buttons/widgets/swipe_navigation.yaml
      widgets:
        # Button 1 - Local relay button
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/local_relay_button.yaml
            vars:
              uid: button_1
              height: $button_height_double
              text: Local Light
              icon: $mdi_lightbulb      
        # Button 2 - Standard light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/switch_button.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: Button 2
              icon: $mdi_lightbulb
              entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
        # Button 3 - Empty button moves the buttons below it down one
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/transparent_empty_button.yaml
            vars:
              uid: empty_3
              height: $button_height_single
        # Button 4 - Dimming (double hight) light button with state updates
        - button: !include
            file: esphome-modular-lvgl-buttons/buttons/dimmer_light_button.yaml
            vars:
              uid: button_4
              height: $button_height_double
              text: RGB light
              icon: $mdi_string_lights
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip

# -------------------------------------------------------------------------
# Fonts and graphics
# -------------------------------------------------------------------------

# I you want to use other MDI icons add them to the list here
font:
  # http://materialdesignicons.com/cdn/7.4.47/
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: mdi_icons_40
    size: 40
    bpp: 8
    glyphs: [
      $mdi_lightbulb,  # mdi-lightbulb
      $mdi_ceiling_light,  # mdi-ceiling-light
      $mdi_lamp,  # mdi-lamp
      $mdi_floor_lamp,  # mdi-floor-lamp
      $mdi_string_lights,  # mdi-string-lights
      $mdi_track_light,  # mdi-track-light
      $mdi_bulkhead_light,  # mdi-bulkhead_light
      $mdi_led_strip,  # mdi-led-strip
      $mdi_coach_lamp,  # mdi-coach-lamp
      $mdi_ceiling_fan_light,  # mdi-ceiling-fan-light
      $mdi_bed,  # mdi-bed
      $mdi_white_balance_sunny,  # mdi-white-balance-sunny
      $mdi_brightness_6,  # mdi-brightness-6

    ]
 
