lvgl:
  page_wrap: true
  theme:
    obj:
      border_width: 0
      scrollable: false      
      pad_all: 0
      radius: 0
      bg_opa: TRANSP
      outline_width: 1
      outline_color: red
    label:
      border_width: 0
      scrollable: false
      text_color: black
      outline_width: 1
      outline_color: red
    image:
      border_width: 0
      scrollable: false
      outline_width: 1
      outline_color: red
    button:
      text_font: $text_font
      checkable: false
      press_lock: false
      scroll_on_focus: true
      radius: 25px
      width: $button_width
      height: $button_height_single
      pad_all: 10px
      shadow_width: 0 # This is required even though the default is supposed to be 0
      bg_opa: cover
      bg_color: $button_off_color
      text_color: $label_off_color

  style_definitions:
    - id: page_style
      bg_color: black
      bg_opa: cover
      pad_all: 5

select:
  - platform: template
    name: "Current Theme"
    id: current_theme
    icon: mdi:theme-light-dark
    optimistic: true
    options:
      - Dark
      - Light
    initial_option: Light
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(current_theme).current_option() == "Dark";'
            then:
              - lvgl.style.update:
                  id: page_style
                  bg_color: black
                  text_color: white
              - lvgl.widget.redraw
        - if:
            condition:
              - lambda: 'return id(current_theme).current_option() == "Light";'
            then:
              - lvgl.style.update:
                  id: page_style
                  bg_color: white
                  text_color: black
              - lvgl.widget.redraw