---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    password: "995593244899"
  power_save_mode: none

captive_portal:

# web_server:
#   port: 80
#   version: 3
# # Uncomment the lines above to enable the web server again.
  
