---
lvgl:
  style_definitions:
    - id: boot_screen_style
      text_font: nunito_20
      text_color: black # not working at the moment
      pad_all: 2
  pages:
    - id: info_screen
      styles: boot_screen_style
      <<: !include
        file: ../widgets/swipe_navigation.yaml
      widgets:
        - obj:
            width: 100%
            height: 100%
            layout:
              type: GRID
              grid_rows: [ content,content,content,content,content,content,content,content,content,content ]
              grid_columns: [ FR(45), FR(55) ]
              pad_column: 4
              pad_row: 5
            widgets:
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "ESPHome Version:"
              - label:
                  id: esphome_version_label
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Loading..."
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Build Date:"
              - label:
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text:
                    format: "%s - %s"
                    args: [__DATE__, __TIME__]
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 3
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "MAC Address:"
              - label:
                  id: connected_mac_label
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 3
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "00:00:00:00:00:00"
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 4
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "IP Address:"
              - label:
                  id: ip_address_label
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 4
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "0.0.0.0"
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 5
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Connected SSID"
              - label:
                  id: connected_ssid_label
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 5
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Updating..."
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 6
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "WiFi Strength"
              - label:
                  id: wifi_signal_db_percent_label
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 6
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Updating..."
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 7
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Device Name:"
              - label:
                  id: device_name_label
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 7
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Updating..."
              - qrcode:
                  id: cp_login
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 8
                  grid_cell_x_align: START
                  grid_cell_y_align: CENTER
                  pad_left: 10
                  pad_top: 10
                  size: 100
                  text: "WIFI:S:mynetwork;T:WPA;P:password;;"
              - qrcode:
                  id: cp_ip_address
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 8
                  grid_cell_x_align: START
                  grid_cell_y_align: CENTER
                  pad_left: 10
                  pad_top: 10
                  size: 100
                  text: "http://192.168.4.1"
              - label:
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 9
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "Captive Portal Wi-Fi"
              - label:
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 9
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
                  text: "CP config page"
        - button:
            align: bottom_right
            radius: 15
            width: 100
            height: 50
            widgets:
             - label:
                 text_color: white
                 align: center
                 text: "Exit"
            on_press:
              - lvgl.page.show: main_page


