---
# Dimmer light switch button
# vars:
  # uid:
  # height:
  # text:
  # icon:
  # entity_id:
height: ${height}
id: button_${uid}
widgets:
  - label:
      text_font: $icon_font
      align: top_left
      id: icon_${uid}
      text: ${icon}
  - label:
      align: bottom_left
      id: label_${uid}
      text: ${text}
  - slider:
      align: top_right
      id: slider_${uid}
      x: -5
      y: 5
      width: 40
      height: 165
      min_value: 0
      max_value: 255
      radius: 10
      knob:
        pad_top: -15
        pad_bottom: -15 
        radius: 5        
        bg_color: $label_on_color
      indicator:
        radius: 0
        bg_color: $label_off_color
      on_release:
        - homeassistant.action:
            action: light.turn_on
            data:
              entity_id: ${entity_id}
              brightness: !lambda return int(x);
on_short_click:
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: ${entity_id}
# on_long_press disabled to save flash space
on_long_press:
    then:
      lvgl.page.show: ${uid}_light_page


      
  
