---
# Local relay button with LONG-PRESS toggle (hold to toggle)
# vars:
  # uid:
  # height:
  # text:
  # icon:
  # entity_id:
height: ${height}
id: button_${uid}
widgets:
  - label:
      text_font: $icon_font
      align: top_left
      id: icon_${uid}
      text: ${icon}
  - label:
      align: bottom_left
      id: label_${uid}
      text: ${text}
on_long_press:
    light.toggle: local_light_${uid}
