---
# Scene button with LONG-PRESS activation (hold to activate)
# vars:
  # uid:
  # height:
  # text:
  # icon:
  # entity_id:
height: ${height}
id: button_${uid}
widgets:
  - label:
      text_font: $icon_font
      align: top_left
      id: icon_${uid}
      text: ${icon}
  - label:
      align: bottom_left
      id: label_${uid}
      text: ${text}
on_long_press:
    homeassistant.service:
      service: scene.turn_on
      data:
        entity_id: ${entity_id}
